version: "3"
services:
  db:
    image: mysql:8.0
    networks:
      - choborin_net 
    volumes:
      - mysqlvol:/var/lib/mysql
      - /var/nodeapp/node_modules
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOTPASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD 
  web:
    build: .
    depends_on:
      - db
    networks:
      - choborin_net
    volumes:
      - ./src:/var/nodeapp
      - /var/nodeapp/node_modules
    ports:
      - 8080:3000
    environment:
      MYSQL_SERVER: mysql
      MYSQL_HOST: db
      MYSQL_NAME: $DB_NAME
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD 
    tty: true 
networks:
  choborin_net:
volumes:
  mysqlvol:

